# Supabase Project Configuration

[functions]

# -------------------------
# create-checkout-session
# -------------------------
[functions.create-checkout-session]
verify_jwt = false
import_map = "./functions/create-checkout-session/deno.json"
entrypoint = "./functions/create-checkout-session/index.ts"

# -------------------------
# stripe-webhook
# -------------------------
[functions.stripe-webhook]
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"
